### PR TITLE
Auto cone pickup

### PR DESCRIPTION
**Pull request by gbuckholtz**
Merging in Auto cone pickup.  The code may not work perfectly, but the structure is there so Autonomous programmers can have something to work with.

### CODE REVIEW

**Comment by gbuckholtz** [comment]
comment from @jumpydolphin  :We might need to merge his new request in. I just tried the code we have and it doesn't work. It drives and Mathews code runs but it makes the robot do the diagonal thing

**Comment by gbuckholtz** [comment]
@jumpydolphin, you deployed the pull request code to the robot and it was doing the diagonal thing?

**Comment by gbuckholtz** [comment]
@knutt5  or @Kabinet0 ,  has this code already been put into the main branch?

**Comment by Kabinet0** [comment]
Yes, but it is a few days old and is still being actively developed, I should be able to merge it in a day or two. @gbuckholtz

**Comment by gbuckholtz** [comment]
Just going to do a little experiment.  I am going to close this pull request and open up another one.  I want to see if it changes  the target compare file from the main branch.

**Pull request closed without merging**
